version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install pytest
            
 
      - run:
          name: Run Sparse Matrix
          command: |
            pytest test_sparse_recommender.py

      - run:
          name: Build image
          command: |
            docker build -t ssangras/sparse_movie_recommender:latest .

      - run:
          name: push image
          command: |
           echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push "$DOCKER_USERNAME"/movierecommender:"${CIRCLE_SHA1}"

 
workflows:
  version: 2
  build:
    jobs:
      - build