version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install pytest
            
 
      - run:
          name: Run Sparse Matrix
          command: |
            pytest test_sparse_recommender.py
 
workflows:
  version: 2
  build:
    jobs:
      - build